import 'reflect-metadata';
import 'dotenv/config';
import mongoose from 'mongoose';
import { hashPassword } from './common/utils/password';
import { UserSchema } from './users/schemas/user.schema';
import { CategorySchema } from './categories/schemas/category.schema';
import { BrandSchema } from './brands/schemas/brand.schema';
import { ProductSchema } from './products/schemas/product.schema';

const run = async () => {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/golden_barrel';
  await mongoose.connect(uri);

  const User = mongoose.model('User', UserSchema);
  const Category = mongoose.model('Category', CategorySchema);
  const Brand = mongoose.model('Brand', BrandSchema);
  const Product = mongoose.model('Product', ProductSchema);

  await User.deleteMany({});
  await Category.deleteMany({});
  await Brand.deleteMany({});
  await Product.deleteMany({});

  const categories = await Category.insertMany([
    { name: 'Whisky', slug: 'whisky' },
    { name: 'Gin', slug: 'gin' },
    { name: 'Vodka', slug: 'vodka' },
    { name: 'Wine', slug: 'wine' },
    { name: 'Champagne', slug: 'champagne' },
    { name: 'Beer', slug: 'beer' },
  ]);

  const brands = await Brand.insertMany([
    { name: 'Johnnie Walker', slug: 'johnnie-walker' },
    { name: 'Colombo', slug: 'colombo' },
    { name: "Jacob's Creek", slug: 'jacobs-creek' },
    { name: 'The Macallan', slug: 'the-macallan' },
    { name: 'Absolut', slug: 'absolut' },
    { name: 'Jam Jar', slug: 'jam-jar' },
    { name: 'Moet & Chandon', slug: 'moet-chandon' },
    { name: 'Glenfiddich', slug: 'glenfiddich' },
    { name: "Jack Daniel's", slug: 'jack-daniels' },
    { name: 'Heineken', slug: 'heineken' },
  ]);

  const categoryBySlug = Object.fromEntries(categories.map((c: any) => [c.slug, c]));
  const brandBySlug = Object.fromEntries(brands.map((b: any) => [b.slug, b]));
  const brandImage: Record<string, string> = {
    'johnnie-walker': 'https://upload.wikimedia.org/wikipedia/commons/4/49/Johnnie_Walker_wordmark.svg',
    colombo: '/Company-Colombo.jpg',
    'jacobs-creek': '/Jacobs_Creek.png',
    'the-macallan': '/the-macallan-logo.png',
    absolut: 'https://upload.wikimedia.org/wikipedia/commons/1/16/Logo-absolut.svg',
    'jam-jar': '/jam jar.png',
    'moet-chandon': 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Logo_Mo%C3%ABt_%26_Chandon_2025.png',
    glenfiddich: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Glenfiddich_Text_Logo.svg',
    'jack-daniels': '/jackdaniels.png',
    heineken: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Heineken_logo_%281%29.png',
  };

  const sampleProducts = [
    {
      name: 'Johnnie Walker Red Label',
      slug: 'johnnie-walker-red-label',
      category: 'whisky',
      brand: 'johnnie-walker',
      price: 32,
      stock: 80,
      images: [brandImage['johnnie-walker']],
      abv: 40,
      volume: 750,
      description: 'Bold, smoky blend that shines in highballs and classic cocktails.',
      tags: ['blended', 'smoky', 'cocktails'],
    },
    {
      name: 'Johnnie Walker Black Label 12Y',
      slug: 'johnnie-walker-black-label-12y',
      category: 'whisky',
      brand: 'johnnie-walker',
      price: 48,
      stock: 65,
      images: ['/Johnnie-Walker-Black-Label-New-600x703.jpg.webp'],
      abv: 40,
      volume: 750,
      description: 'Rich, smooth, and smoky with a balanced, layered finish.',
      tags: ['12-year', 'blended', 'smooth'],
    },
    {
      name: 'Johnnie Walker Double Black',
      slug: 'johnnie-walker-double-black',
      category: 'whisky',
      brand: 'johnnie-walker',
      price: 58,
      stock: 50,
      images: ['/Johnnie-Walker-Double-Black-441x517.png.webp'],
      abv: 40,
      volume: 750,
      description: 'Intense smoke with deeper, richer flavors.',
      tags: ['smoky', 'bold', 'peat'],
    },
    {
      name: 'Johnnie Walker Gold Label Reserve',
      slug: 'johnnie-walker-gold-label-reserve',
      category: 'whisky',
      brand: 'johnnie-walker',
      price: 78,
      stock: 36,
      images: ['/Johnnie-Walker-Gold-Label-Reserve.jpg.webp'],
      abv: 40,
      volume: 750,
      description: 'Honey, vanilla, and creamy notes with a luxurious mouthfeel.',
      tags: ['honey', 'vanilla', 'creamy'],
    },
    {
      name: 'Johnnie Walker Blue Label',
      slug: 'johnnie-walker-blue-label',
      category: 'whisky',
      brand: 'johnnie-walker',
      price: 220,
      stock: 14,
      images: ['/Johnnie-Walker-Blue-Label-with-Box-441x517.png.webp'],
      abv: 40,
      volume: 750,
      description: 'Luxury blend with exceptional smoothness and depth.',
      tags: ['premium', 'luxury', 'smooth'],
    },
    {
      name: 'Colombo No.7 London Dry Gin',
      slug: 'colombo-no-7-london-dry-gin',
      category: 'gin',
      brand: 'colombo',
      price: 44,
      stock: 52,
      images: ['/Colombo-7-Gin-1-600x703.jpg.webp'],
      abv: 47,
      volume: 700,
      description: 'Sri Lankan botanicals with a spicy, aromatic profile.',
      tags: ['london-dry', 'botanical', 'spicy'],
    },
    {
      name: 'Colombo Arrack Gin',
      slug: 'colombo-arrack-gin',
      category: 'gin',
      brand: 'colombo',
      price: 46,
      stock: 40,
      images: ['/Colombo-No-8-Gin-441x517.png.webp'],
      abv: 45,
      volume: 700,
      description: 'Craft gin with a tropical, herbal twist.',
      tags: ['craft', 'tropical', 'herbal'],
    },
    {
      name: "Jacob's Creek Shiraz",
      slug: 'jacobs-creek-shiraz',
      category: 'wine',
      brand: 'jacobs-creek',
      price: 18,
      stock: 90,
      images: ['/Jacobs-Creek-Shiraz-Rose-600x703.jpg.webp'],
      abv: 13.5,
      volume: 750,
      description: 'Spicy red wine with bold berry flavors.',
      tags: ['red', 'spicy', 'berry'],
    },
    {
      name: "Jacob's Creek Cabernet Sauvignon",
      slug: 'jacobs-creek-cabernet-sauvignon',
      category: 'wine',
      brand: 'jacobs-creek',
      price: 19,
      stock: 85,
      images: ['/Jacobs-Creek-Cabernet-Sauvignon.jpg.webp'],
      abv: 13.5,
      volume: 750,
      description: 'Full-bodied with oak and dark fruit notes.',
      tags: ['red', 'oak', 'full-bodied'],
    },
    {
      name: "Jacob's Creek Chardonnay",
      slug: 'jacobs-creek-chardonnay',
      category: 'wine',
      brand: 'jacobs-creek',
      price: 17,
      stock: 88,
      images: ['/Jacobs-Creek-Chardonnay.jpg'],
      abv: 12.5,
      volume: 750,
      description: 'Smooth white wine with citrus and soft oak.',
      tags: ['white', 'citrus', 'smooth'],
    },
    {
      name: "Jacob's Creek Moscato",
      slug: 'jacobs-creek-moscato',
      category: 'wine',
      brand: 'jacobs-creek',
      price: 16,
      stock: 92,
      images: ['/Jacobs-Creek-Sparkling-Rose.jpg'],
      abv: 8,
      volume: 750,
      description: 'Light, fruity, and gently sweet.',
      tags: ['sweet', 'fruity', 'light'],
    },
    {
      name: 'Macallan 12 Double Cask',
      slug: 'macallan-12-double-cask',
      category: 'whisky',
      brand: 'the-macallan',
      price: 92,
      stock: 35,
      images: [brandImage['the-macallan']],
      abv: 40,
      volume: 700,
      description: 'Vanilla, honey, and gentle oak with a silky finish.',
      tags: ['single-malt', 'vanilla', 'honey'],
    },
    {
      name: 'Macallan 12 Sherry Oak',
      slug: 'macallan-12-sherry-oak',
      category: 'whisky',
      brand: 'the-macallan',
      price: 98,
      stock: 30,
      images: [brandImage['the-macallan']],
      abv: 40,
      volume: 700,
      description: 'Rich dried fruit and warm spice from sherry casks.',
      tags: ['sherry', 'rich', 'dried-fruit'],
    },
    {
      name: 'Macallan 15 Double Cask',
      slug: 'macallan-15-double-cask',
      category: 'whisky',
      brand: 'the-macallan',
      price: 140,
      stock: 22,
      images: [brandImage['the-macallan']],
      abv: 43,
      volume: 700,
      description: 'Smooth and complex with layered oak sweetness.',
      tags: ['15-year', 'complex', 'oak'],
    },
    {
      name: 'Macallan 18 Sherry Oak',
      slug: 'macallan-18-sherry-oak',
      category: 'whisky',
      brand: 'the-macallan',
      price: 320,
      stock: 10,
      images: [brandImage['the-macallan']],
      abv: 43,
      volume: 700,
      description: 'Premium single malt with deep oak and dried fruit.',
      tags: ['18-year', 'premium', 'oak'],
    },
    {
      name: 'Absolut Original',
      slug: 'absolut-original',
      category: 'vodka',
      brand: 'absolut',
      price: 28,
      stock: 120,
      images: ['/Absolut-Vodka-750ml-600x703.jpg'],
      abv: 40,
      volume: 750,
      description: 'Clean, neutral vodka for cocktails and sipping.',
      tags: ['vodka', 'clean', 'classic'],
    },
    {
      name: 'Absolut Citron',
      slug: 'absolut-citron',
      category: 'vodka',
      brand: 'absolut',
      price: 30,
      stock: 95,
      images: ['/Absolut-Citron-441x517.jpg'],
      abv: 40,
      volume: 750,
      description: 'Bright lemon flavor for refreshing mixes.',
      tags: ['flavored', 'lemon', 'citrus'],
    },
    {
      name: 'Absolut Raspberry',
      slug: 'absolut-raspberry',
      category: 'vodka',
      brand: 'absolut',
      price: 30,
      stock: 90,
      images: ['/Absolut-Raspberri-1-600x703.jpg.webp'],
      abv: 40,
      volume: 750,
      description: 'Sweet, fruity raspberry infusion.',
      tags: ['flavored', 'raspberry', 'sweet'],
    },
    {
      name: 'Absolut Vanilla',
      slug: 'absolut-vanilla',
      category: 'vodka',
      brand: 'absolut',
      price: 30,
      stock: 92,
      images: ['/Absolut-Vanilia-1.jpg.webp'],
      abv: 40,
      volume: 750,
      description: 'Dessert-style vanilla notes with smooth finish.',
      tags: ['flavored', 'vanilla', 'dessert'],
    },
    {
      name: 'Jam Jar Sweet Shiraz',
      slug: 'jam-jar-sweet-shiraz',
      category: 'wine',
      brand: 'jam-jar',
      price: 16,
      stock: 100,
      images: ['/Jam-Jar-Sweet-Red-Blend-600x703.jpg.webp'],
      abv: 12,
      volume: 750,
      description: 'Sweet red wine with ripe berry flavors.',
      tags: ['sweet', 'red', 'berry'],
    },
    {
      name: 'Jam Jar Sweet White',
      slug: 'jam-jar-sweet-white',
      category: 'wine',
      brand: 'jam-jar',
      price: 15,
      stock: 96,
      images: ['/Jam-Jar-Sweet-White-600x703.jpg.webp'],
      abv: 12,
      volume: 750,
      description: 'Light, fruity, and easy to enjoy.',
      tags: ['sweet', 'white', 'fruity'],
    },
    {
      name: 'Moet Brut Imperial',
      slug: 'moet-brut-imperial',
      category: 'champagne',
      brand: 'moet-chandon',
      price: 55,
      stock: 70,
      images: [brandImage['moet-chandon']],
      abv: 12,
      volume: 750,
      description: 'Crisp and elegant with fine bubbles.',
      tags: ['brut', 'crisp', 'elegant'],
    },
    {
      name: 'Moet Rose Imperial',
      slug: 'moet-rose-imperial',
      category: 'champagne',
      brand: 'moet-chandon',
      price: 60,
      stock: 62,
      images: [brandImage['moet-chandon']],
      abv: 12,
      volume: 750,
      description: 'Fruity and fresh with vibrant berry notes.',
      tags: ['rose', 'fruity', 'fresh'],
    },
    {
      name: 'Moet Ice Imperial',
      slug: 'moet-ice-imperial',
      category: 'champagne',
      brand: 'moet-chandon',
      price: 65,
      stock: 58,
      images: [brandImage['moet-chandon']],
      abv: 12,
      volume: 750,
      description: 'Designed to be served over ice.',
      tags: ['ice', 'summer', 'refreshing'],
    },
    {
      name: 'Glenfiddich 12',
      slug: 'glenfiddich-12',
      category: 'whisky',
      brand: 'glenfiddich',
      price: 52,
      stock: 55,
      images: [brandImage.glenfiddich],
      abv: 40,
      volume: 700,
      description: 'Fresh pear and soft oak with a clean finish.',
      tags: ['12-year', 'fresh', 'pear'],
    },
    {
      name: 'Glenfiddich 15 Solera',
      slug: 'glenfiddich-15-solera',
      category: 'whisky',
      brand: 'glenfiddich',
      price: 78,
      stock: 40,
      images: [brandImage.glenfiddich],
      abv: 40,
      volume: 700,
      description: 'Rich and smooth with layered complexity.',
      tags: ['15-year', 'smooth', 'rich'],
    },
    {
      name: 'Glenfiddich 18',
      slug: 'glenfiddich-18',
      category: 'whisky',
      brand: 'glenfiddich',
      price: 120,
      stock: 26,
      images: [brandImage.glenfiddich],
      abv: 40,
      volume: 700,
      description: 'Deep oak character with warming spice.',
      tags: ['18-year', 'oak', 'spice'],
    },
    {
      name: 'Glenfiddich 21 Reserva',
      slug: 'glenfiddich-21-reserva',
      category: 'whisky',
      brand: 'glenfiddich',
      price: 210,
      stock: 12,
      images: [brandImage.glenfiddich],
      abv: 40,
      volume: 700,
      description: 'Rum cask finish with a luxurious profile.',
      tags: ['21-year', 'rum-cask', 'premium'],
    },
    {
      name: "Jack Daniel's Old No. 7",
      slug: 'jack-daniels-old-no-7',
      category: 'whisky',
      brand: 'jack-daniels',
      price: 32,
      stock: 90,
      images: ['/Jack-Daniels-No-27-Gold-441x517.jpg'],
      abv: 40,
      volume: 750,
      description: 'Classic Tennessee whiskey with smooth character.',
      tags: ['tennessee', 'classic', 'smooth'],
    },
    {
      name: "Jack Daniel's Gentleman Jack",
      slug: 'jack-daniels-gentleman-jack',
      category: 'whisky',
      brand: 'jack-daniels',
      price: 40,
      stock: 70,
      images: ['/Gentleman-Jack-441x517.webp'],
      abv: 40,
      volume: 750,
      description: 'Extra smooth with refined charcoal mellowing.',
      tags: ['smooth', 'premium', 'tennessee'],
    },
    {
      name: "Jack Daniel's Honey",
      slug: 'jack-daniels-honey',
      category: 'whisky',
      brand: 'jack-daniels',
      price: 30,
      stock: 85,
      images: ['/Jack-Daniels-Honey-600x703.jpg'],
      abv: 35,
      volume: 750,
      description: 'Sweet honey notes layered over classic whiskey.',
      tags: ['flavored', 'honey', 'sweet'],
    },
    {
      name: "Jack Daniel's Fire",
      slug: 'jack-daniels-fire',
      category: 'whisky',
      brand: 'jack-daniels',
      price: 30,
      stock: 82,
      images: ['/JD-Tennesse-Fire-1-600x703.jpg'],
      abv: 35,
      volume: 750,
      description: 'Cinnamon spice with a warm finish.',
      tags: ['flavored', 'cinnamon', 'spice'],
    },
    {
      name: 'Heineken Original',
      slug: 'heineken-original',
      category: 'beer',
      brand: 'heineken',
      price: 10,
      stock: 160,
      images: [brandImage.heineken],
      abv: 5,
      volume: 330,
      description: 'Crisp and refreshing lager.',
      tags: ['lager', 'crisp', 'refreshing'],
    },
    {
      name: 'Heineken Silver',
      slug: 'heineken-silver',
      category: 'beer',
      brand: 'heineken',
      price: 11,
      stock: 150,
      images: [brandImage.heineken],
      abv: 4,
      volume: 330,
      description: 'Light and smooth lager.',
      tags: ['lager', 'light', 'smooth'],
    },
    {
      name: 'Heineken 0.0',
      slug: 'heineken-0-0',
      category: 'beer',
      brand: 'heineken',
      price: 9,
      stock: 140,
      images: ['/heineken-00-bottle.png'],
      abv: 0,
      volume: 330,
      description: 'Alcohol-free with the classic Heineken taste.',
      tags: ['non-alcoholic', 'lager', 'refreshing'],
    },
  ].map((product) => ({
    ...product,
    categoryId: categoryBySlug[product.category]._id,
    brandId: brandBySlug[product.brand]._id,
  }));

  await Product.insertMany(sampleProducts);

  const saltRounds = Number(process.env.BCRYPT_SALT_ROUNDS || 12);
  const adminPassword = await hashPassword('AdminPass1', saltRounds);
  const staffPassword = await hashPassword('StaffPass1', saltRounds);
  const customerPassword = await hashPassword('CustomerPass1', saltRounds);

  await User.insertMany([
    {
      email: 'admin@goldenbarrel.com',
      passwordHash: adminPassword,
      name: 'Admin User',
      dob: new Date('1990-01-01'),
      isAgeVerified: true,
      role: 'ADMIN',
    },
    {
      email: 'staff@goldenbarrel.com',
      passwordHash: staffPassword,
      name: 'Staff User',
      dob: new Date('1992-01-01'),
      isAgeVerified: true,
      role: 'STAFF',
    },
    {
      email: 'customer@goldenbarrel.com',
      passwordHash: customerPassword,
      name: 'Customer User',
      dob: new Date('1995-01-01'),
      isAgeVerified: true,
      role: 'CUSTOMER',
    },
  ]);

  await mongoose.disconnect();
  console.log('Seed complete');
};

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
